org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.1.1
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

mod_version=0.1.0
maven_group=com.github.ryanf
archives_base_name=hotbar-qol
release_type=alpha
modrinth_project_id=NAkSF4Vx

fabric_api_version=0.145.4+26.1.1
junit_version=5.10.3
